steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/mediku-backend', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/mediku-backend']
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'beta',
              'run',
              'deploy',
              'mediku-backend',
              '--image',
              'gcr.io/$PROJECT_ID/mediku-backend',
              '--region',
              'asia-southeast2',
              '--platform',
              'managed',
              '--allow-unauthenticated',
          ]
image: 'gcr.io/$PROJECT_ID/mediku-backend'
